CREATE DATABASE test_db;

CREATE TABLE test_db.foo(
	id SERIAL,
	PRIMARY KEY(id),
	created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	last_updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	name VARCHAR(20) NOT NULL);

CREATE TABLE test_db.bar(
	id SERIAL,
	PRIMARY KEY(id),
	created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	last_updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP);

ALTER TABLE test_db.foo
	ADD COLUMN bar_id BIGINT UNSIGNED NOT NULL,
	ADD FOREIGN KEY(bar_id) REFERENCES test_db.bar(id),
	UNIQUE KEY(bar_id));

ALTER TABLE test_db.bar
	ADD COLUMN foo_id BIGINT UNSIGNED NOT NULL,
	ADD FOREIGN KEY(foo_id) REFERENCES test_db.foo(id),
	UNIQUE KEY(foo_id));

